var port = process.env.PORT || '3001',
    production = process.env.NODE_ENV === 'production';

// Run webpack dev server or prod server, depending on env.
if (production) {
  startExpressServer();
} else {
  startWebpackDevServer();
}

// Creates a simple Express server and serves index.html, along with
// the static assets within the dist folder. In our case, the only file that
// will be served is our bundled JS app, which is generated by 
// webpack prior to starting this server.
function startExpressServer() {
  // Set up express
  var express = require('express'),
      app = express(),
      path = require('path');

  app.use('/dist', express.static('dist'));
  app.get('*', function(req, res, next) {
    res.sendFile(path.join(__dirname, 'index.html'));
  });

  app.listen(port);
  console.log('Server is running on: ' + port);
}

// Creates a a WebpackDevServer with hot reloading enabled.
function startWebpackDevServer() {
  // Start up webpack
  var webpack = require('webpack'),
      WebpackDevServer = require('webpack-dev-server'),
      config = require('./webpack.dev.config');

  new WebpackDevServer(webpack(config), {
    publicPath: config.output.publicPath,
    hot: true,
    historyApiFallback: true
  }).listen(port, 'localhost', function (err, result) {
    if (err) {
      return console.log(err);
    }

    console.log('Listening on port ' + port);
  });
}